version: "3"

tasks:
  portf:
    desc: Port-forward prometheus from the current kube ctx
    vars:
      ns: '{{ .ns | default "monitoring" }}'
      svc: '{{ .svc | default "kube-prometheus-stack-prometheus"}}'
      local: '{{ .local | default "9090" }}'
      remote: '{{ .remote | default "9090" }}'
    cmds:
      - kubectl -n {{ .ns }} port-forward svc/{{ .svc }} {{ .local }}:{{ .remote }}

  query:
    desc: Run the query sub-command
    silent: true
    cmds:
      - go run main.go query

  serve:
    desc: Run the http server
    cmds:
      - go generate
      - go run main.go serve

  docker:build:
    desc: Build the docker image
    requires:
      vars:
        - tag
    cmds:
      - docker build . -t henrywhitaker3/prompage:{{ .tag }}

  docker:run:
    desc: Build and run the docker image
    vars:
      tag:
        sh: head -n 10 /dev/random | md5sum | cut -c1-6
    cmds:
      - task: docker:build
        vars:
          tag: '{{ .tag }}'
      - docker run --net=host --rm -v $(pwd)/prompage.yaml:/prompage.yaml henrywhitaker3/prompage:{{ .tag }} {{ .CLI_ARGS }}

  helm:install:
    desc: Install the helm chart
    vars:
      values: '{{ .values | default "chart/values.yaml" }}'
      ns: '{{ .ns | default "prompage" }}'
      name: '{{ .name | default "prompage" }}'
    cmds:
      - helm upgrade --install -f chart/{{ .values }} -n {{ .ns }} {{ .name }} chart/

  default:
    silent: true
    cmds:
      - task -l
