name: Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      packages: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Get chart version
        run: |
          CHART_VERSION=$(cat chart/Chart.yaml | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+$")
          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if chart exists
        id: chartExists
        run: |
          set +e
          docker manifest inspect ghcr.io/${{ github.repository }}-helm:v${{ env.CHART_VERSION }}
          rc=$?
          set -e
          if [ $rc -eq 0 ]; then
            echo Chart version already exists
            echo "CHART_EXISTS=yes" >> $GITHUB_OUTPUT
          else
            echo Chart version does not exist
            echo "CHART_EXISTS=no" >> $GITHUB_OUTPUT
          fi

      - name: Push chart
        if: steps.chartExists.outputs.CHART_EXISTS == 'no'
        uses: appany/helm-oci-chart-releaser@d94988c92bed2e09c6113981f15f8bb495d10943 # v0.5.0
        with:
          name: prompage-helm
          repository: ${{ github.repository_owner }}
          tag: "v${{ env.CHART_VERSION }}"
          path: chart
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: "true"
